[default]
test_var = "test variable"
host_ip = "0.0.0.0"
host_port = 8000
mongodb_url = ""
env_name = "default"

[development]
env_name = "development"
mongodb_url = "mongodb://localhost:27017"

[dev_testing]
env_name = "testing"
mongodb_url = "mongodb://localhost:27017"